### ISSUE TITLE
Use ENV over Cargo.toml?

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/heroku-buildpack-rust#16]
Should an ENV flag be used over the `Cargo.toml` to configure which version to use from `multirust`?

I'd argue that using `Cargo.toml` makes it more reproducible and declarative.

**Comment by ramn** [comment]
In Rust 1.7, I get this compiler warning: `unused manifest key: target.heroku.version`

Also, from irc:

> 21:25 @acrichto steveklabnik: ramn: unfortunately there's currently no way to disable the warning

**Comment by Hoverbear** [comment]
Yeah! You should only see this when not building on Heroku and it's quite harmless. I've been thinking of better ways to do this but currently I think `[target]` is rather appropriate.

Any suggestions?

**Comment by ramn** [comment]
Perhaps a file in the git root called `.rust-version`. Rubyists use a `.ruby-version` file so there is a precedent.

**Comment by Hoverbear** [comment]
Ahhh hmm that's an interesting idea. I quite like the `Cargo.toml` because it conveys a semantic meaning like "This application is possible to target for Heroku".

**Comment by ramn** [comment]
Yes it would be nice to be able to reuse the Cargo.toml rather than introducing a new file. On the other hand, it seems cargo doesn't like custom fields, so maybe that goes against the intentions of the file.

**Comment by pascalw** [comment]
I would prefer an environment variable as well, I prefer not to have provider/environment specific stuff in my application.

We could, for example, check a `$RUST_VERSION` environment variable and if that's not defined fallback to the current behaviour?

**Comment by Hoverbear** [comment]
@pascalw I'd accept a pull request doing that happily, otherwise I think I will add this feature when I have some time. :)

**Comment by pascalw** [comment]
I'll try to send a PR later today. I already added the functionality in my fork, but I still have to add a test and update docs.
