### ISSUE TITLE
Use Rustup?

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/heroku-buildpack-rust#21]
http://rustup.rs/ exists now, we should probably use that.

**Comment by LeoBorai** [comment]
Hey @Hoverbear !

I think this is an excellent idea! Any plans on merging #27 ?

**Comment by Hoverbear** [comment]
Hey! I suggest you compile the binaries locally or on CI and ship them to Heroku. :)

I should probably archive this repo.

**Comment by LeoBorai** [comment]
Roger! Thanks!
