### ISSUE TITLE
Cannot find std libraries?

### ISSUE THREAD

**Issue by lephyrius** [Hoverbear/heroku-buildpack-rust#23]
When I try to run the application I get this error:
`2016-06-09T12:49:20.847819+00:00 app[web.1]: ./target/release/test: error while loading shared libraries: libstd-8102e29f.so: cannot open shared object file: No such file or directory` 
I have no idea what could be wrong.

**Comment by Hoverbear** [comment]
Hmmm this is very strange. Could you give me your `Cargo.toml` and `src/main.rs`?

**Comment by Hoverbear** [comment]
Closed due to no response.
