### ISSUE TITLE
Compiled slug size is too large

### ISSUE THREAD

**Issue by RoxasShadow** [Hoverbear/heroku-buildpack-rust#24]
I'm not sure if this is a good place for this issue but I'm quite stuck on it.

Basically in the last days I'm having a problem deploying a project on heroku because the [slug size](https://devcenter.heroku.com/articles/slug-size) is too big (`Compiled slug size: 307.2M is too large (max is 300M).` – appears just after the compilation of all the deps).

I created a `.slugignore` containing `/target/release/deps` (I also tried with `target/release/deps`) but nothing changed. I also noticed that folder to be large 400-500M, thing that sounds quite weird to me but probably that's the size after being compressed.

The project itself (without `.git` and `target`) is just 180K, anyway.

_Update:_ for now I solved by purging the git cache as suggested [here](https://robots.thoughtbot.com/how-to-reduce-a-large-heroku-compiled-slug-size), but I feel like this is not the ideal way to solve this problem, like the `.slugignore` would most likely be.

**Comment by Hoverbear** [comment]
Hmmmm interesting. I'd be happy to accept a PR on this, or if you could give me more details about what steps the buildpack could take I can work on an update.

**Comment by RoxasShadow** [comment]
What I was thinking is to tell Heroku to not compress the folders that are used for compiling the projects, like `~/target/release/deps` and `~/target/release/build`, thing that would remove a couple of hundreds of megabytes. But as I wrote in the issue description, I wasn't able to do this via `.slugignore` so I can't provide a proper PR.

**Comment by Hoverbear** [comment]
Darnit! :(

**Comment by Hoverbear** [comment]
So I think this is because of [this line](https://github.com/Hoverbear/heroku-buildpack-rust/blob/master/bin/compile#L74) which just copies over the cache. This means that old deps eventually build up. I think we can do this better.

**Comment by RoxasShadow** [comment]
Inside the `target/` we actually need only the executable in most of the cases. If you can confirm this, we could only move the actual executable, replicating the folders structure.

**Comment by RoxasShadow** [comment]
@Hoverbear I occurred in https://github.com/ethcore/parity/issues/808 – not sure if it's worth opening a new issue as it kinda looks that could be solved by this one. Not sure though.

For now I can solve it manually through `heroku run bash`, btw.

**Comment by Hoverbear** [comment]
So thinking about this more, perhaps the best way is letting people build on their dev machine as a MUSL linux then just uploading the binary.

**Comment by RoxasShadow** [comment]
I agree on that, but we have to find a place where put the binary in order to keep the automated deploys working (i.e. via the `/deploy/github` button). How does S3 sound to you?

**Comment by RoxasShadow** [comment]
GitHub doesn't like `--amend`s :(

**Comment by Hoverbear** [comment]
@roxasshadow Now in this particular case, no :(

**Comment by Hoverbear** [comment]
Closing this due to #28. Though it is not _entirely_ solved.
