### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by TomasHubelbauer** [Hoverbear/heroku-buildpack-rust#25]
Thank you for this amazing buildpack! Just deployed a hello world server successfully just following the readme instructions (!!!)! Previously, I tried the emk's buildpack, but I couldn't get it to work. That's not to say that it is bad, it's just to say that I'm not too bright and this buildpack rocks!

**Comment by Hoverbear** [comment]
=D!

Thank you! This does need some work, there are currently two big issues:
- The Cargo cache eventually inflates and busts the slug limit. I'm not really sure how to address this.
- We need to update to rustup soon. :)

If you feel like tackling any of these I'd be more than happy to help! The first is definitely easier.

**Comment by TomasHubelbauer** [comment]
I'm new to both Rust and Heroku, so probably no PR from me. :) I did wonder why Rustup wasn't used, though, but I looked through the other issues and saw that you are aware of it so I didn't point it out. I've never used Multirust before.

**Comment by Hoverbear** [comment]
Yeah -- I'm still trying to figure out the best way of handling Rustup since it doesn't offer the same level of configuration as Multirust. I've actually made partial patches like three times now and end up throwing them out since they don't make me happy.
